name: C Network Programming CI

on:
  push:
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install build tools (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        sudo apt-get update || true
        sudo apt-get install -y gcc make || true
        which gcc && gcc --version

    - name: Install build tools (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install make mingw
        echo "CC=gcc" >> $GITHUB_ENV
        echo "PATH=/c/ProgramData/chocolatey/bin:/mingw64/bin:$PATH" >> $GITHUB_ENV

